name: "Bug"
description: 버그 리포트
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 재현 방법
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 기대 동작

  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
