name: "Feature"
description: 새로운 기능 구현 요청
title: "[FEAT] "
labels: ["feat"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 기능 요약
      placeholder: 구현할 기능을 간략히 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 배경 / 동기
      placeholder: 왜 이 기능이 필요한가요?

  - type: textarea
    id: acceptance
    attributes:
      label: 완료 조건 (Acceptance Criteria)
      placeholder: |
        - [ ] 조건 1
        - [ ] 조건 2
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 참고 자료
      placeholder: 대규모 시스템 설계 기초 Ch.4, 링크 등
